"""Realtor and Property test setup

Revision ID: f5fdda9023ce
Revises: 
Create Date: 2021-03-07 00:39:43.570592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fdda9023ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propertyName', sa.String(length=64), nullable=False),
    sa.Column('squareFootage', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_propertyName'), 'property', ['propertyName'], unique=False)
    op.create_table('realtor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_realtor_email'), 'realtor', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_realtor_email'), table_name='realtor')
    op.drop_table('realtor')
    op.drop_index(op.f('ix_property_propertyName'), table_name='property')
    op.drop_table('property')
    # ### end Alembic commands ###
